using ContentManagementSystem.EntityFrameworkCore;
using Xunit;

namespace ContentManagementSystem.EntityFrameworkCore;

public class ContentManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<ContentManagementSystemEntityFrameworkCoreFixture>
{

}
