using Volo.Abp;

namespace ContentManagementSystem.EntityFrameworkCore;

public abstract class ContentManagementSystemEntityFrameworkCoreTestBase : ContentManagementSystemTestBase<ContentManagementSystemEntityFrameworkCoreTestModule>
{

}
